enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"$lib/g11n",
	"App.css",
	"App.js",
	"Food.js",
	"FoodList.js",
	"About.js",
	"Picture.js",
	"model/FoodModel.js",
	"model/CanteenModel.js",
	"model/CanteenService.js",
	"model/DateModel.js",
	"model/ReichenhainerCanteen.js",
	"model/StraNaCanteen.js",
	"model/AppModel.js"
);
